- pdk:
    name: "Power Development Kit"
    scouts:
      - name: atomic-github
        type: scout-github.rb
        access_token: 8f0cfc4d20f73ad5e9f094a197afae6f4aa0e5d3
        queries:
          - "user:projectatomic user:openshift is:open label:focus:devex"

      - name: rh-bz
        type: scout-bugzilla.py
        username: yellowhat
        password: yhat1002$
        server: https://bugs.eclipse.org
        queries:
          - "status_whiteboard=RHT"

      - name: jboss-jira
        type: scout-jira.py
        username: jiralint
        password: drauc3er
        server: https://issues.jboss.org
        queries:
          - "filter = ds_maint"
